"""Common modern loanword kana extensions (kana_romanizer_spec.md Part III, §24)."""

MODERN_KANA_EXTENSIONS: dict[str, str] = {
    "いぇ": "ye",
    "うぃ": "wi",
    "うぇ": "we",
    "うぉ": "wo",
    "ゔ": "vu",
    "ゔぁ": "va",
    "ゔぃ": "vi",
    "ゔぇ": "ve",
    "ゔぉ": "vo",
    "ゔゅ": "vyu",
    "しぇ": "she",
    "じぇ": "je",
    "ちぇ": "che",
    "つぁ": "tsa",
    "つぃ": "tsi",
    "つぇ": "tse",
    "つぉ": "tso",
    "てぃ": "ti",
    "とぅ": "tu",
    "でぃ": "di",
    "どぅ": "du",
    "ふぁ": "fa",
    "ふぃ": "fi",
    "ふぇ": "fe",
    "ふぉ": "fo",
    "ふゅ": "fyu",
    "くぁ": "kwa",
    "くぃ": "kwi",
    "くぇ": "kwe",
    "くぉ": "kwo",
    "ぐぁ": "gwa",
    "ぐぃ": "gwi",
    "ぐぇ": "gwe",
    "ぐぉ": "gwo",
}
